<?php

namespace Tests;

use Orchestra\Testbench\TestCase;
use WyattCast44\LaravelSchema\LaravelSchemaServiceProvider;

class AutoGenerateDisabledTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp();

        $this->loadMigrationsFrom(__DIR__ . '/database/migrations');
    }

    protected function getPackageProviders($app)
    {
        return [LaravelSchemaServiceProvider::class];
    }

    protected function getEnvironmentSetUp($app)
    {
        $app['config']->set('schema.auto_generate', false);

        $app['config']->set('schema.path',  __DIR__ . '/database/schemas');
    }

    public function test_it_doesnt_generate_any_schema_files()
    {
        $this->artisan('migrate', ['--database' => 'testing']);

        $this->assertFalse(file_exists(__DIR__ . '/database/schemas/users.schema.json'));
        $this->assertFalse(file_exists(__DIR__ . '/database/schemas/password_resets.schema.json'));
    }
}
